### ISSUE TITLE
sync_extruder_load not working 

### ISSUE THREAD

**Issue by rwijnhov** [moggieuk/Happy-Hare#104]
I want to use sync_extruder_load as i only want to sync during load. But that doesn't work on the latest version i get error:
Option 'sync_extruder_load' is not valid in section 'mmu'

**Comment by moggieuk** [comment]
Correct, that option is no longer valid because HH ALWAYS synced during load.  Initially the option was there because there were sometimes issues with stepper synchronization when using the "manual_steppers" as a base.  Now that I implement a second toolhead to control the MMU these worries are gone, hence HH does the best thing which in this case is to sync the load operation.

**Comment by rwijnhov** [comment]
ok tnx for the feedback.
