### ISSUE TITLE
possibility to "servo up" when the extruder catch the filamaent ?

### ISSUE THREAD

**Issue by salocain** [moggieuk/Happy-Hare#127]
when the filament is loaded , to the extruder (i'm in bowden ) the servo is down for send filament to the extruder gear --> ok normal

but when the filament is keep by extruder the servo and gear motor stay engaged ,  it's possible to go back to the V1 mod --> when the filament is pick up by extruder --> desengaged servo and gear motor ?

or it's in config , but the things i test don't do this

**Comment by moggieuk** [comment]
I'm not sure what you are asking for.  HH will decide when to use gear/extruder synchronization during the load and unload process.   I took away the choice because it don't make sense not to sync gear and extruder while trying to enter the extruder...
The ERCF_Software_V1 has a lot of "clever" options but fundamentally they were there because of the unreliability of stepper syncing - that is now very reliable
