### ISSUE TITLE
gate_parking_distance Ignored

### ISSUE THREAD

**Issue by ajsomething** [moggieuk/Happy-Hare#130]
gate_parking_distance located in mmu_parameters.cfg is ignored on feed for MMU_CALIBRATE_BOWDEN.
The correct amount is pulled past the encoder, but is ignored when starting the sequence for calibration. 

Setup, 
ERCF - BTT motion sensor - Toolhead
I have unplugged the ERCF "Normal" encoder due to the plethora of issues, however, can not force calibration to use the ERCF because the correct amount is not fed back to get the filament to the encoder. when gate_parking_distance is set to 50, an extra 50MM is retracted correctly but only 15-20 is fed in.
 

Error:
An issue with the MMU has been detected whilst out of a print
Reason: Calibration of Bowden length (on Gate #0) failed. Aborting, because:
Error loading filament at gate - not enough movement detected at encoder

**Comment by moggieuk** [comment]
As you said `gate_parking_distance` is the distance from the homing point (encoder or mmu_gate sensor) back into the gate.  If I understand you correctly, you have replaced the ERCF encoder for the BTT sensor (BTW this is completely untested because the new Binky encoder is ultra reliable -- you would also need to set the `default_encoder_resolution` and also I would be suspicious of whether the BTT sensor can handle the fast speeds).

Because this sits further from the gate you increased `gate_parking_distance`.  ok.
To ensure the gate is loaded, when using encoder, the MMU has to move a small distance to overshoot the encoder and then subtract that overshoot.  That move distance is controlled by `gate_homing_max` which default to 70mm.  You might need to make this 100mm for your setup.
