### ISSUE TITLE
Internal error during connect: module "toolhead" has no attribute "BUFFER_TIME_HIGH"

### ISSUE THREAD

**Issue by Gr33n5murf** [moggieuk/Happy-Hare#189]
as the title suggests i get this error when including the various mmu.cfg

**Comment by ningpj** [comment]
Is your klipper deployment up to date as a lot of changes have been pushed out by the klipper team to the python toolhead object which has created a dependency between the two.  Updating klipper should solve this issue if you aren’t already running a currecnt version eg v0.12.0-102-g9f41f53c

**Comment by JesNoFear** [comment]
I am getting this error now too, since I got happy hare installed.

 Internal error during connect: 'module' object has no attribute 'BUFFER_TIME_HIGH'

![image](https://github.com/moggieuk/Happy-Hare/assets/51521144/6fa24a8d-8dbd-4388-ba9f-85d80578dc01)

the BUFFER_TIME_HIGH is a setting in OctoPrint that makes the buffer larger so your prints don't pause because the buffer ran out.

https://github.com/Klipper3d/klipper/issues/2629

I have narrowed it down to [include mmu/base/mmu_parameters.cfg], ill keep digging

**Comment by JesNoFear** [comment]
Error in klippy.log:
MMU Hardware Initialization -------------------------------
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/pi/klipper/klippy/extras/mmu.py", line 6180, in load_config
    return Mmu(config)
  File "/home/pi/klipper/klippy/extras/mmu.py", line 634, in __init__
    self._setup_mmu_hardware(config)
  File "/home/pi/klipper/klippy/extras/mmu.py", line 647, in _setup_mmu_hardware
    self.mmu_toolhead = MmuToolHead(config, self.homing_extruder)
  File "/home/pi/klipper/klippy/extras/mmu_toolhead.py", line 39, in __init__
    self.move_queue.set_flush_time(toolhead.BUFFER_TIME_HIGH) # Happy Hare: Use base class (older klipper)
AttributeError: 'module' object has no attribute 'BUFFER_TIME_HIGH'

**Comment by JesNoFear** [comment]
> Is your klipper deployment up to date as a lot of changes have been pushed out by the klipper team for the python toolhead object which has created dependencies between the two. Updating klipper should solve this issue if you aren’t already running a current version eg v0.12.0-102-g9f41f53c.

You are correct, updating to Firmware version: v0.12.0-114-ga77d0790-dirty does correct the problem.

it does however break the ability to adjust the buffer size in the printer config, which is sad.

I had been on Firmware version: v0.11.0-276-ge9bf2d4c-dirty, and last time i had checked it was current, which may had been back in dec / jan.

**Comment by moggieuk** [comment]
Tell me more about the buffer size in config?  This would be the klipper change right?  Happy Hare is just following along with klipper/toolhead changes...

**Comment by JesNoFear** [comment]
> Tell me more about the buffer size in config?  This would be the klipper change right?  Happy Hare is just following along with klipper/toolhead changes...

Sure, so historically klipper had a command you could enter in your config to modify the high buffer, it allowed systems that are a little slower, to buffer more commands so the controller did run out of buffer and pause while waiting for the buffer to be filled again. This was a fix for octoprint in particular, changing the standard buffer of 2.0 to 10 to allow a constant flow of commands.

In the latest release of klipper, it looks like they removed that functionality of being able to re-define the buffer, which is only related in the sense that you have to use the newer version of klipper in order for happy hare to work.

The solution at this point to correct the issue is to comment out the line in the config (buffer_time_high), and modify the toolhead.py directly, changing the buffer to the desired size. (Line 190)

I have not sifted through all the changes between v 0.11.0-276 and v 0.12.0-114 to see when it was removed and if there is any overlap where the command existed and is functional with the buffer_time_high. But my guess is it was either removed by accident / thinking it wasn't being used or was intentional as it was causing timing issues with some other operations.

**Comment by jorgi** [comment]
I have 3v3KE and almost finished TradRack in hope somehow I get it working together (was aware about closed version of klipper on my Ender, but hey, the challenge it is!). I connected yesterday night my ERCF Easy brd to my printer, uploaded all configs and found out the "BUFFER_TIME_HIGH" error is going to stop my challenge.
Happy to found this thread as there is almost nothing on the topic to be found in the net... and this light up a chance to complete my challenge.
I will be more than happy in testing or otherwise helping.

**Comment by k1-801** [comment]
> I have 3v3KE
> the "BUFFER_TIME_HIGH" error is going to stop my challenge.

The patch in #388 should work for you as well, since it shares the mainboard with K1. Since you already have HHv2 installed, you only really need to replace the `mmu_toolhead.py` file (in 'extras') with the one from my branch.

**Comment by jorgi** [comment]
I'm stuck in other place now, after applying the patch BUFFER_TIME_HIGH error disappeared but other error appears:

`[INFO] 2024-09-04 20:22:48,718 [root] [mcu:_mcu_identify:823] Loaded MCU 'mmu' 120 commands (?-20240824_231541-539011865e59 / gcc
: (15:12.2.rel1-1) 12.2.1 20221205 binutils: (2.40-2+18+b1) 2.40)
MCU 'mmu' config: ADC_MAX=4095 CLOCK_FREQ=48000000 MCU=samd21g18a PWM_MAX=255 RESERVE_PINS_USB=PA24,PA25 STATS_SUMSQ_BASE=256 STE
PPER_BOTH_EDGE=1
[INFO] 2024-09-04 20:22:48,720 [root] [serialhdl:connect_pipe:167] mcu 'rpi': Starting connect
[INFO] 2024-09-04 20:22:48,725 [root] [serialhdl:_bg_thread:40] mcu 'rpi': current nice = -20
[INFO] 2024-09-04 20:22:49,411 [root] [mcu:_mcu_identify:823] Loaded MCU 'rpi' 104 commands (v0.11.0-372-gb9ad7605 / gcc: (Ingeni
c Linux-Release5.1.0-Default(xburst2(fp64)+glibc2.29) 2021.12-22 10:52:10) 7.2.0 binutils: (Ingenic Linux-Release5.1.0.-Default(x
burst2(fp64)+glibc2.29) 2021.12-22 08:55:37) 2.27)
MCU 'rpi' config: ADC_MAX=4095 CLOCK_FREQ=50000000 MCU=linux PCA9685_MAX=4096 PWM_MAX=32768 STATS_SUMSQ_BASE=256 build_machine_ui
d=May 18 202311:46:31
[INFO] 2024-09-04 20:22:49,413 [root] [temperature_mcu:_mcu_identify:85] mcu_temperature 'mcu' nominal base=378.658537 slope=-804
.878049
[INFO] 2024-09-04 20:22:49,435 [root] [mcu:_send_config:712] Sending MCU 'mcu' printer configuration...
[INFO] 2024-09-04 20:22:49,451 [root] [serialhdl:handle_output:301] mcu 'mcu': #output: allocMax=3804 usedMax=0
[INFO] 2024-09-04 20:22:49,456 [root] [mcu:_connect:785] Configured MCU 'mcu' (3794 moves)
[ERROR] 2024-09-04 20:22:49,463 [root] [klippy:_connect:248] Unhandled exception during connect
Traceback (most recent call last):
  File "/usr/share/klipper/klippy/klippy.py", line 198, in _connect
    cb()
  File "/usr/share/klipper/klippy/mcu.py", line 761, in _connect
    self._send_config(None)
  File "/usr/share/klipper/klippy/mcu.py", line 691, in _send_config
    cb()
  File "/usr/share/klipper/klippy/mcu.py", line 73, in _build_config
    self._trdispatch_mcu = ffi_main.gc(ffi_lib.trdispatch_mcu_alloc(
OverflowError: can't convert negative number to unsigned
`

At the same time machine is barely responsive, sometimes even ssh doesn't work and the most interesting stuff, screen goes crazy, e.g.:

[https://photos.app.goo.gl/VwUPoAcddqYHstbP8]

No clue where to look now, might try to install older version of klipper on Easy BRD but not sure if that might relate with this crazy screen behaviour.

**Comment by k1-801** [comment]
> I'm stuck in other place now, after applying the patch BUFFER_TIME_HIGH error disappeared but other error appears:

Have you solved the issue?
It appears it it caused by a klipper firmware version mismatch, which means you'd have to flash the MMU board with Klipper firmware that is as old as the Ender 3 KE's klipper (ideally, with Creality's sources - linked above). If you want to use mainline klipper, it'll 100% work, but you need it to be no newer than December 2023 (before the commit https://github.com/Klipper3d/klipper/commit/bafb126abd77edd0cb2e5ae3b5d99ff83272594c ).

**Comment by FelixOstermeier** [comment]
Yes, flashing the MMU board with the latest version of Klipper v 0.11.0 did resolve this issue. I couldn't use the "Creality Klipper for K1" as make fails on the PRTouch files.

**Comment by jorgi** [comment]
Yes, installing KE version of klipper on TR MCU helped, i can see now klipper connecting to MCU but then stops at MMU sanity checks with this:

```Calibration settings file (mmu_vars.cfg) not found. Check [save_variables] section in mmu_macro_vars.cfg
Also ensure you only have a single [save_variables] section defined in your printer config and it defines a file that contains the necessary Happy Hare configuration```

The file is there and I removed the save_variables entry from KAMP so really not sure what's wrong, but digging deeper.

**Comment by k1-801** [comment]
> The file is there and I removed the save_variables entry from KAMP so really not sure what's wrong, but digging deeper.
>
> 
It's probably the "Save Z-offset" feature

**Comment by jorgi** [comment]
I disabled all additional includes, just in case, so it's something else.

**Comment by jorgi** [comment]
Ok, i pulled repo and repeated configuration, klipper started, can move Servo, so it works !!
Now need to get everything together and go to next step, but the most difficult part is done I guess!!
Am I the first one to have Ender V3VKE (close to) working with Tradrack ? :-)

**Comment by jorgi** [comment]
and Happy Hare of couurse :)
