### ISSUE TITLE
Different behaviour when only loading or unloading vs doing a full change

### ISSUE THREAD

**Issue by dzeta621** [moggieuk/Happy-Hare#307]
I use a kinda dangerous macro to park my toolhead out of the soft travel limits of my printer during tool change and I absolutly need to use a custom macro to restore the old position. For now I added this restore macro on user_post_load_extension and user_post_unload_extension for safety but when I resquest a full change I have a lot of useless moves.
Can I somehow detect if i'm loading another filament after the unload for exemple ? This way I can bypass the restore macro when doing a full change.

**Comment by moggieuk** [comment]
I think you can use the available MMU printer variables to determine what you need.  Look at `next_tool`.  This should not be set (probably -1) if doing an `MMU_EJECT` or `MMU_UNLOAD` rather than a `MMU_CHANGE_TOOL`.

More details on variables in wiki: https://github.com/moggieuk/Happy-Hare/wiki/Printer-Variables
