### ISSUE TITLE
skip calibrate encoder when using tradrack

### ISSUE THREAD

**Issue by LE1ED4523** [moggieuk/Happy-Hare#317]
I have set my mmu_vendor in mmu_parameters.cfg to tradrack
![PixPin_2024-06-18_12-59-05](https://github.com/moggieuk/Happy-Hare/assets/140297184/1f102782-302c-426c-a5bf-bae878553555)
I calibrated other parameters but when I want to load it tell me prerequsite calibration steps are not complete. Please run: MMU_CALIBRATE_ENCODER
![PixPin_2024-06-18_13-03-38](https://github.com/moggieuk/Happy-Hare/assets/140297184/76c31f20-419a-433d-bc98-b9652e838391)
wiki only say _Calibrate your encoder (if fitted)_  how can I calibrate it or skip the calibration if I don't have any encoder

**Comment by moggieuk** [comment]
Can you give me more context on where you are in your journey...

Did you call "MMU_PRELOAD"?  That requires full calibration but the encoder calibration should be optional so maybe setup is incomplete elsewhere and I suspect it is this:

Without encoder:
```
gate_homing_endstop: mmu_gate
```
This is because you have a gate sensor on the Tradrack so need to use that and not the encoder measurements for parking.

This isn't automatic because many Tradrack users have encoder, but I can probably improve the install over time..
