### ISSUE TITLE
Buffer Array

### ISSUE THREAD

**Issue by alidaf** [moggieuk/Happy-Hare#324]
In your instructions you state: "I run mine with a standalone Raspberry Pi attached to my buffer array and can control multiple MMU's with it." What is a buffer array? I'm trying to determine whether I need to replace the display on my Voron 2.4 with a new touch display but this implies that I don't need to.

**Comment by moggieuk** [comment]
Buffer array is simply a line of filament buffers (like ERCT).  Mine are in a cabinet and I attached my rpi with KlipperScreen to that because it sits above the printer.

KlipperScreen can be attached to rpi on the printer OR can be on a separate rpi.  I prefer separate so I can control all my printers from one panel..

**Comment by alidaf** [comment]
Makes sense. Thank you.
