### ISSUE TITLE
Toolhead filament sensor if triggered causing toolhead pausing leading to blobs

### ISSUE THREAD

**Issue by gennro** [moggieuk/Happy-Hare#51]
Found an issue if the tool head sensor is triggered during a print it will cause the tool head to pause momentarily resulting in a blob on the print.

Klipper.log will have these run out events through out.
Filament Sensor toolhead_sensor: runout event detected, Time 47115.16

[klipper log - Filament Sensor toolhead_sensor run.txt](https://github.com/moggieuk/Happy-Hare/files/12644716/klipper.log.-.Filament.Sensor.toolhead_sensor.run.txt)

**Comment by moggieuk** [comment]
This is because klipper (i think mistakenly) defaults "pause_on_runout" to True.  Although I force this to false, the fact it was true during startup causes klipper to configure an empty gcode handler instead of non at all.
Workaround: explicitly set `pause_on_runout: False` in mmu_hardware.cfg.   That said, the new push will have logic to correct the empty gcode handlers.

As an aside, the toolhead sensor should not trigger during a print. Even at 10000mm/s/s a 0.89g 6mm ball would exert 100 time less force that is needed to press the microswitch.  I wonder if the particular switch you are using is on the edge of the trigger point..?

Anyway, marking as fixed in next release.
